-- Schema for riders, stations, and their m2m relationship.

CREATE TABLE "riders" (
  "id" INTEGER,
  "name" TEXT,
  PRIMARY KEY("id") -- make sure the id column has the PRIMARY KEY constraint.
);

CREATE TABLE "stations" (
  "id" INTEGER,
  "name" TEXT NOT NULL UNIQUE, --Park Street
  "line" TEXT NOT NULL, --Red line
  PRIMARY KEY("id")
);

CREATE TABLE "visits" (
  "rider_id" INTEGER,
  "station_id" INTEGER,
  -- the PK for visits is auto-generated by sqlite, it is not explicitly typed here.
  -- because rider_id and station_id both reference PKs on other tables, they are BOTH foreign keys.
  FOREIGN KEY("rider_id") REFERENCES "riders"("id"), -- REFERENCES "tableName"("columnName")
  FOREIGN KEY("station_id") REFERENCES "stations"("id")
);

-- .read schema.sql